#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define NUMERO_MARCOS 40
#define SISTEMA_OPERATIVO -1
#define CAPACIDAD_MARCO 5
#define MARCOS_RESERVADOS_SO 2
#define RANURAS 4
#define SEGUNDO 1000
#define PROCESO_NULO 0

#endif // CONSTANTES_H_INCLUDED
