#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED
#define ESC 27
#define PRODUCTOR 0
#define CONSUMIDOR 1
#define SEGUNDO 1000
#define CAPACIDAD_CONTENEDOR 22


#endif // CONSTANTES_H_INCLUDED
